---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metricsviews-admin-rolebinding
roleRef:
   kind: Role
   name: metricsviews-admin-role  #The role name you defined in the Role configuration
   apiGroup: rbac.authorization.k8s.io
subjects:
  - kind : User
    name: metricsviews    #The name of the user to give the role to
    apiGroup: rbac.authorization.k8s.io
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metricsviews-reader-rolebinding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: metricsviews-reader-role
  apiGroup: rbac.authorization.k8s.io
